"""create blog posts table with foreign key

Revision ID: 32498e2a60d3
Revises: 701065f8abbf
Create Date: 2025-07-14 17:21:11.662223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32498e2a60d3'
down_revision: Union[str, None] = '701065f8abbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'blog_posts', 'rss_feeds', ['feed_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    # ### end Alembic commands ###
