"""Change book mark relation to blog post

Revision ID: 888f4eddb1d5
Revises: d52896e628cf
Create Date: 2025-08-20 20:29:47.828634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888f4eddb1d5'
down_revision: Union[str, None] = 'd52896e628cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('blog_post_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('bookmarks_feed_id_fkey'), 'bookmarks', type_='foreignkey')
    op.create_foreign_key(None, 'bookmarks', 'blog_posts', ['blog_post_id'], ['id'])
    op.drop_column('bookmarks', 'feed_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('feed_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bookmarks', type_='foreignkey')
    op.create_foreign_key(op.f('bookmarks_feed_id_fkey'), 'bookmarks', 'rss_feeds', ['feed_id'], ['id'])
    op.drop_column('bookmarks', 'blog_post_id')
    # ### end Alembic commands ###
