"""create rss feed table

Revision ID: 98586b602dfe
Revises: 1111f0c452e0
Create Date: 2025-07-14 16:18:38.909924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98586b602dfe'
down_revision: Union[str, None] = '1111f0c452e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rss_feeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feed_url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=511), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('last_fetched_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_fetched_status', sa.String(length=50), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default='NOW()', nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default='NOW()', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rss_feeds')
    # ### end Alembic commands ###
