"""create feed category

Revision ID: b991fb9fdbf3
Revises: 24d65a75989a
Create Date: 2025-08-15 15:27:11.514916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b991fb9fdbf3'
down_revision: Union[str, None] = '24d65a75989a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_categories',
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['feed_id'], ['rss_feeds.id'], ),
    sa.PrimaryKeyConstraint('feed_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed_categories')
    # ### end Alembic commands ###
